In [2]:
import pandas as pd

df = pd.read_csv(r'C:\Users\hp\Downloads\python\pokemon_data.csv')
#print(df.tail(6))

#df = pd.read_csv(r'C:\Users\hp\Downloads\python\pokemon_data.txt', delimiter ='\t')
print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [ ]:
#print(df.columns) # read column names 

#print(df[['Name', 'Attack','Speed']][0:4]) # read each column

#print(df.iloc[0:6]) # read rows 

#print(df.iloc[5,1]) # read a specfic location

#for index , rows in df.iterrows():            # read rows 
    #print(index, rows['Name'])

#df.loc[df['Type 1']=="Fire"] 

#df.loc[(df['Type 1'] == "Fire") & (df['Speed'] > 80) & (df["Type 2"]=="Flying")]        # and & , Or | conditions

#df.describe()

#df.sort_values('Type 1', ascending=True)

#df.sort_values(['Name','Type 1','HP'], ascending=[1,0, 1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [ ]:
#making changes to data 

#df['Total'] = df['Speed'] + df['Attack'] 
#df['Total']=df.iloc[:,4:9].sum(axis=1)

#df=df.drop(columns=['Total'])

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244

In [2]:
#df.to_csv('modfied.csv',index=False)

#df.to_xlsx('modfied.xlsx',index=False)
#df.to_csv('modfiled.txt', index=False, sep='\t')

In [31]:
#new_df= df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]

#new_df.to_csv('filtered.csv')

#new_df.reset_index(drop=True, inplace=True)

df.loc[(df['Name'].str.contains('Mega')) & (df['Type 1'].str.contains('Gra')) & (df['HP']<100)]

#new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False

In [ ]:
import re 

#df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]

#df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I ,regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

In [ ]:
#df.loc[df['Type 1']=='whatever','Type 1']='Grass'

#df.loc[(df['Type 1'] == 'Grass') & (df['Speed']==45),'Attack']='49'

#df.loc[(df['Type 1'] == 'Grass') & (df['Speed']==45),['Attack' ,'Defense']]=[100, 200]


# df= pd.read('modifed.csv')

[100, 200]

In [33]:
#df.groupby(['Type 1']).mean(numeric_only=True)
#df.groupby(['Type 1'])[['HP', 'Attack']].mean(numeric_only=True).sort_values(['HP','Type 1'], ascending=False)

#df.groupby(['Type 1']).sum()

#df.groupby(['Type 1']).count()

df['Count']=1

df.groupby(['Type 1', 'Type 2','HP']).count()['Count']

Type 1  Type 2    HP
Bug     Electric  50     1
                  70     1
        Fighting  80     2
        Fire      55     1
                  85     1
                        ..
Water   Rock      54     1
                  55     1
                  74     1
                  100    1
        Steel     84     1
Name: Count, Length: 343, dtype: int64

In [44]:
new_df=pd.DataFrame(columns=df.columns)

for df in pd.read_csv(r'C:\Users\hp\Downloads\python\pokemon_data.csv', chunksize=20):
    results=df.groupby(['Type 1']).count()

    new_df=pd.concat([new_df, results])
    print(new_df)

       # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug    7    7    NaN      5  7      7       7       7       7     7
Fire   5    5    NaN      3  5      5       5       5       5     5
Grass  4    4    NaN      4  4      4       4       4       4     4
Water  4    4    NaN      0  4      4       4       4       4     4

      Generation Legendary
Bug            7         7
Fire           5         5
Grass          4         4
Water          4         4
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
Bug               4         4
Fairy             2         2
Fire              2         2
Grass             3         3
Ground            2         2
Normal            4         4
Poison            2         2
Water             1         1
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1
Fighting  5    5    NaN      0  5      5       5       5       5     5
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Psychic   4    4    NaN      0  4      4       4       4       4     4
Water     6    6    NaN      3  6      6       6       6       6     6

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
Bug               4         4
Fairy             2         2
Fire              2         2
Grass             3         3
Ground            2         2
Normal            4         4
Poison            2         2
Water             1         1
Fighting          5         5
Fire              2         2
Grass             3         3
Psychic           4         4
Water             6         6
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1
Fighting  5    5    NaN      0  5      5       5       5       5     5
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Psychic   4    4    NaN      0  4      4       4       4       4     4
Water     6    6    NaN      3  6      6       6       6       6     6
Electric  2    2    NaN      2  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Ghost     1    1    NaN      1  1      1       1       1       1     1
Normal    3    3    NaN      3  3      3       3       3       3     3
Poison    2    2    NaN      0  2      2       2       2       2     2
Rock      3    3    NaN      3  3      3       3       3       3     3
Water     7    7    NaN      5  7      7       7       7       7     7

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
Bug               4         4
Fairy             2         2
Fire              2         2
Grass             3         3
Ground            2         2
Normal            4         4
Poison            2         2
Water             1         1
Fighting          5         5
Fire              2         2
Grass             3         3
Psychic           4         4
Water             6         6
Electric          2         2
Fire              2         2
Ghost             1         1
Normal            3         3
Poison            2         2
Rock              3         3
Water             7         7
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1
Fighting  5    5    NaN      0  5      5       5       5       5     5
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Psychic   4    4    NaN      0  4      4       4       4       4     4
Water     6    6    NaN      3  6      6       6       6       6     6
Electric  2    2    NaN      2  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Ghost     1    1    NaN      1  1      1       1       1       1     1
Normal    3    3    NaN      3  3      3       3       3       3     3
Poison    2    2    NaN      0  2      2       2       2       2     2
Rock      3    3    NaN      3  3      3       3       3       3     3
Water     7    7    NaN      5  7      7       7       7       7     7
Electric  2    2    NaN      0  2      2       2       2       2     2
Fighting  2    2    NaN      0  2      2       2       2       2     2
Ghost     3    3    NaN      3  3      3       3       3       3     3
Grass     2    2    NaN      2  2      2       2       2       2     2
Ground    3    3    NaN      1  3      3       3       3       3     3
Normal    1    1    NaN      0  1      1       1       1       1     1
Poison    2    2    NaN      0  2      2       2       2       2     2
Psychic   2    2    NaN      0  2      2       2       2       2     2
Rock      1    1    NaN      1  1      1       1       1       1     1
Water     2    2    NaN      0  2      2       2       2       2     2

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
Bug               4         4
Fairy             2         2
Fire              2         2
Grass             3         3
Ground            2         2
Normal            4         4
Poison            2         2
Water             1         1
Fighting          5         5
Fire              2         2
Grass             3         3
Psychic           4         4
Water             6         6
Electric          2         2
Fire              2         2
Ghost             1         1
Normal            3         3
Poison            2         2
Rock              3         3
Water             7         7
Electric          2         2
Fighting          2         2
Ghost             3         3
Grass             2         2
Ground            3         3
Normal            1         1
Poison            2         2
Psychic           2         2
Rock              1         1
Water             2         2
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1
Fighting  5    5    NaN      0  5      5       5       5       5     5
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Psychic   4    4    NaN      0  4      4       4       4       4     4
Water     6    6    NaN      3  6      6       6       6       6     6
Electric  2    2    NaN      2  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Ghost     1    1    NaN      1  1      1       1       1       1     1
Normal    3    3    NaN      3  3      3       3       3       3     3
Poison    2    2    NaN      0  2      2       2       2       2     2
Rock      3    3    NaN      3  3      3       3       3       3     3
Water     7    7    NaN      5  7      7       7       7       7     7
Electric  2    2    NaN      0  2      2       2       2       2     2
Fighting  2    2    NaN      0  2      2       2       2       2     2
Ghost     3    3    NaN      3  3      3       3       3       3     3
Grass     2    2    NaN      2  2      2       2       2       2     2
Ground    3    3    NaN      1  3      3       3       3       3     3
Normal    1    1    NaN      0  1      1       1       1       1     1
Poison    2    2    NaN      0  2      2       2       2       2     2
Psychic   2    2    NaN      0  2      2       2       2       2     2
Rock      1    1    NaN      1  1      1       1       1       1     1
Water     2    2    NaN      0  2      2       2       2       2     2
Bug       3    3    NaN      2  3      3       3       3       3     3
Electric  1    1    NaN      0  1      1       1       1       1     1
Fire      1    1    NaN      0  1      1       1       1       1     1
Grass     1    1    NaN      0  1      1       1       1       1     1
Ground    1    1    NaN      1  1      1       1       1       1     1
Ice       1    1    NaN      1  1      1       1       1       1     1
Normal    4    4    NaN      0  4      4       4       4       4     4
Psychic   1    1    NaN      1  1      1       1       1       1     1
Water     7    7    NaN      1  7      7       7       7       7     7

         Generation Legendary
Bug               7         7
Fire              5         5
Grass             4         4
Water             4         4
Electric          2         2
Ground            2         2
Normal            8         8
Poison            8         8
Bug               4         4
Fairy             2         2
Fire              2         2
Grass             3         3
Ground            2         2
Normal            4         4
Poison            2         2
Water             1         1
Fighting          5         5
Fire              2         2
Grass             3         3
Psychic           4         4
Water             6         6
Electric          2         2
Fire              2         2
Ghost             1         1
Normal            3         3
Poison            2         2
Rock              3         3
Water             7         7
Electric          2         2
Fighting          2         2
Ghost             3         3
Grass             2         2
Ground            3         3
Normal            1         1
Poison            2         2
Psychic           2         2
Rock              1         1
Water             2         2
Bug               3         3
Electric          1         1
Fire              1         1
Grass             1         1
Ground            1         1
Ice               1         1
Normal            4         4
Psychic           1         1
Water             7         7
          # Name Type 1 Type 2 HP Attack Defense Sp. Atk Sp. Def Speed  \
Bug       7    7    NaN      5  7      7       7       7       7     7
Fire      5    5    NaN      3  5      5       5       5       5     5
Grass     4    4    NaN      4  4      4       4       4       4     4
Water     4    4    NaN      0  4      4       4       4       4     4
Electric  2    2    NaN      0  2      2       2       2       2     2
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    8    8    NaN      6  8      8       8       8       8     8
Poison    8    8    NaN      2  8      8       8       8       8     8
Bug       4    4    NaN      4  4      4       4       4       4     4
Fairy     2    2    NaN      0  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Ground    2    2    NaN      0  2      2       2       2       2     2
Normal    4    4    NaN      2  4      4       4       4       4     4
Poison    2    2    NaN      2  2      2       2       2       2     2
Water     1    1    NaN      0  1      1       1       1       1     1
Fighting  5    5    NaN      0  5      5       5       5       5     5
Fire      2    2    NaN      0  2      2       2       2       2     2
Grass     3    3    NaN      3  3      3       3       3       3     3
Psychic   4    4    NaN      0  4      4       4       4       4     4
Water     6    6    NaN      3  6      6       6       6       6     6
Electric  2    2    NaN      2  2      2       2       2       2     2
Fire      2    2    NaN      0  2      2       2       2       2     2
Ghost     1    1    NaN      1  1      1       1       1       1     1
Normal    3    3    NaN      3  3      3       3       3       3     3
Poison    2    2    NaN      0  2      2       2       2       2     2
Rock      3    3    NaN      3  3      3       3       3       3     3
Water     7    7    NaN      5  7      7       7       7       7     7
Electric  2    2    NaN      0  2      2       2       2       2     2
Fighting  2    2    NaN      0  2      2       2       2       2     2
Ghost     3    3    NaN      3  3      3       3       3       3     3
Grass     2    2    NaN      2  2      2       2       2       2     2
Ground    3    3    NaN      1  3      3       3       3       3     3
Normal    1    1    NaN      0  1      1       1       1       1     1
Poison    2    2    NaN      0  2      2       2       2       2     2
Psychic   2    2    NaN      0  2      2       2       2       2     2
Rock      1    1    NaN      1  1      1       1       1       1     1
Water     2    2    NaN      0  2      2       2       2       2     2
Bug       3    3    NaN      2  3      3       3       3       3     3
Electric  1    1    NaN      0  1      1       1       1       1     1