In [14]:
import pandas as pd

df = pd.read_csv(r'C:\Users\hp\Downloads\python\pokemon_data.csv')
#print(df.tail(6))

#df = pd.read_csv(r'C:\Users\hp\Downloads\python\pokemon_data.txt', delimiter ='\t')
print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [ ]:
#print(df.columns) # read column names 

#print(df[['Name', 'Attack','Speed']][0:4]) # read each column

#print(df.iloc[0:6]) # read rows 

#print(df.iloc[5,1]) # read a specfic location

#for index , rows in df.iterrows():            # read rows 
    #print(index, rows['Name'])

#df.loc[df['Type 1']=="Fire"] 

#df.loc[(df['Type 1'] == "Fire") & (df['Speed'] > 80) & (df["Type 2"]=="Flying")]        # and & , Or | conditions

#df.describe()

#df.sort_values('Type 1', ascending=True)

#df.sort_values(['Name','Type 1','HP'], ascending=[1,0, 1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [ ]:
#making changes to data 

#df['Total'] = df['Speed'] + df['Attack'] 
#df['Total']=df.iloc[:,4:9].sum(axis=1)

#df=df.drop(columns=['Total'])

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,445
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,545
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,244

In [65]:
#df.to_csv('modfied.csv',index=False)

#df.to_xlsx('modfied.xlsx',index=False)
df.to_csv('modfiled.txt', index=False, sep='\t')